version: "2"

services:
  node:
    build:
      context: .
    image: bench-bot
    expose:
      - 4278
    ports:
      - "4278:4278"
    environment:
      PORT: 4278
      IP: "0.0.0.0"
    env_file: dc.env

    restart: always
